### ISSUE TITLE
WBIResourceDistributor for all resources in a vessel

### ISSUE THREAD

**Issue by RealKolago** [Angel-125/Pathfinder#12]
Can you change WBIResourceDistributor so that it discovers **all** resources of a vessel **in flight** and make these available for distribution?

So we need only a distributor part with

	MODULE
	{
		name = WBIResourceDistributor
	}

in it?

Even when I dock a new tanks to a vessel or changing a tank with another tank manager like ConfigurableContainers?

**Comment by Angel-125** [comment]
WBIResourceDistributor only applies to vessels on the ground. In-flight transfers aren't supported.
