### ISSUE TITLE
Feature request(s): GoldStrike/Fishing

### ISSUE THREAD

**Issue by JadeOfMaar** [Angel-125/Pathfinder#20]
Howdy. I thought I'd lay down my ideas/think out loud of what I hope for that requires GoldStrike to work in ocean:
* Parameter to mark a GoldStrike resource as oceanic (to prevent Aurum and so on from appearing while the prospector is splashed).
* Parameters to confine a resource to named planets and named biomes on planets. Laythe has in-ocean biomes and so will the oceans of Galileo's next set of planets.
* Parameter to scale the rarity/chance to appear and/or the distance between prospect points per resource with respect to the prospect distance slider in KSP's Difficulty Settings. This is spoiler: I intend to facilitate super-rare, even legendary sea-dwellers. They should by default be far less able to easily stumble over than Aurum. Opposite, some creatures would by nature be quite common in certain areas of a sea. 

These features aren't incredibly necessary (or urgent in any amount) so there is no rush at all.

**Comment by Angel-125** [comment]
Fixed in current release
