### ISSUE TITLE
EL messes up Omni Converter GUI

### ISSUE THREAD

**Issue by shaman327** [Angel-125/Pathfinder#22]
With EL installed, the Omni Converter window becomes unreadable.  All the text seems to bunch up to the upper left corner. (See screenshots).  The window then becomes unable to remove or move it and going back to the space center does not fix the issue. KSP has to be restarted. The log is spanned with the following error:
" KeyNotFoundException: The given key was not present in the dictionary.
GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)"

I can remove EL and the OC gui works just fine.

KSP.log file
![screenshot2](https://user-images.githubusercontent.com/17481866/52231329-44b23c80-287f-11e9-9036-fba75cc81d24.png)

[KSP.zip](https://github.com/Angel-125/Pathfinder/files/2829477/KSP.zip)

KSP 1.6.1.2401
EL  6.4.0

**Comment by RealKolago** [comment]
Known Bug in OmniConverters.cfg
Change "ConverterName = Smelt Metal" to "ConverterName = Smelt Metal Lab" and it works!

**Comment by shaman327** [comment]
Thanks.  I tried changing the converter name in the OmniConverters.cfg file under all the omniconverters.cfg files in the subfolders of WildBlueIndustries.  Found 3. 
\000WildBlueTools\Templates\ClassicStock\Production
\000WildBlueTools\Templates\Common\Production
\ClassicStockResources\Templates\Production

The last one did not have the  "ConverterName = Smelt Metal" in it.

I reran the test and it is still doing the same thing.  Do I have something installed wrong?

**Comment by RealKolago** [comment]
I changed "GameData\WildBlueIndustries\000WildBlueTools\Templates\ClassicStock\Production\OmniConverters.cfg"

//EL
OMNICONVERTER:NEEDS[Launchpad]
{
	templateTags = lab
	TechRequired = advExploration
	**ConverterName = Smelt Metal Lab**
	description = Smelt metal into metal ore
	StartActionName = Start metal smelter
	StopActionName = Stop metal smelter
	AutoShutdown = false
	UseSpecialistBonus = true
	SpecialistEfficiencyFactor = 0.2
	SpecialistBonusBase = 0.05
	ExperienceEffect = ConverterSkill
	EfficiencyBonus = 1

**Comment by Angel-125** [comment]
Will be fixed in next release. Thanks for the report. :)
