### ISSUE TITLE
OmniWorks remembers when it ought not to

### ISSUE THREAD

**Issue by JadeOfMaar** [Angel-125/Pathfinder#24]
I've discovered that a given OmniWorks: OmniConverter loadout is remembered when not expected. I made a selection for a Hacienda IMF in the VAB, launched the Hacienda, then reverted to the VAB, chose a fresh Hacienda, and my loadout was (still) there. 
I was surprised at the hefty cost of 5100 Equipment at first but it made sense as I reported to you on Discord. 2700 was the base cost and 400 * 6 added onto it.

It goes away when KSP is shutdown but it returns once a craft is opened in the SPH or VAB and it contains a Hacienda with OmniWorks. It can make for needless spending of multiples of 400 Equipment on OmniConverters not wanted in other instances of Hacienda.

**Comment by Angel-125** [comment]
Fixed in next release. Thanks for the info. :)
