### ISSUE TITLE
It's not possible to put Doc Science Lab inside containers

### ISSUE THREAD

**Issue by andreszlima** [Angel-125/Pathfinder#4]
As said in title, I can put Hacienda, Casa or Chuckwagon inside Buckboards with no problem, but it just vanishes with no error messages when I try with Doc Science Lab.

**Comment by DeTourr** [comment]
Having the same issue, need to attach it to the outside of my rocket to get it to Minmus.

**Comment by Angel-125** [comment]
This is a known issue with KIS and the stock MPL part modules. Nothing I can do about it. You'd have the same issue with any part that uses the stock MPL part modules when you try to put the part into a KIS container.
